project:
  type: website
  output-dir: docs


website:
  title: "Lifeng Ren"
  favicon: "img/favicon_io/favicon.ico"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: "Research"
      # - href: cv.qmd
      #   text: "CV"
      - href: teaching.qmd
        text: "Teaching"
      - href: outreach.qmd
        text: "Outreach"

format:
  html:
    theme: [litera, custom.scss]
    css: styles.css
    toc: false
    page-layout: full
    fontsize: 18px
